Added notebook and updated manifest
UniStuttgart-IKR/MINDFulNotebookExamples.jl pull request #1
Opened 2024-01-09 13:01 UTC by Niels1006

2024-01-10 06:37 UTC, filchristou requested changes
Did you think of a different way to add the tsParticles file other than putting it in the `./data/` directory ?

2024-01-10 06:37 UTC, filchristou commented on Project.toml
>  julia = "1.9"
Can you add julia 1.10 here ?
```suggestion
julia = "1.9, 1.10"
```

2024-01-10 06:37 UTC, filchristou commented on Manifest.toml
> +julia_version = "1.9.4"
Can you try that with julia 1.10 ?
```suggestion
julia_version = "1.10"
```

2024-01-10 10:17 UTC, Niels1006 commented
> Did you think of a different way to add the tsParticles file other than putting it in the `./data/` directory ?

No, but I think that will do it for now.

2024-01-11 07:53 UTC, filchristou approved these changes

2024-01-11 07:53 UTC, merged